<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'stringEncode' => array($vendorDir . '/paquettg/string-encode/src'),
    'Racecore\\GATracking' => array($vendorDir . '/ins0/google-measurement-php-client/src'),
    'PHPHtmlParser' => array($vendorDir . '/paquettg/php-html-parser/src'),
    'ImageOptimizer' => array($vendorDir . '/ps/image-optimizer/src'),
);
